apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: tienda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources/datasources.yaml  # Ruta donde se montará la configuración de datasources
          subPath: datasources.yaml
      volumes:
      - name: grafana-datasources
        configMap:
          name: grafana-datasources-configmap  # Nombre del ConfigMap que contiene la configuración de datasources
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources-configmap
  namespace: tienda
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus-service.tienda.svc.cluster.local:9090
        basicAuth: false
        isDefault: false
        version: 1
        editable: false
        jsonData:
          httpMethod: GET
      - name: Loki
        type: loki
        uid: loki
        access: proxy
        orgId: 1
        url: http://loki-service.tienda.svc.cluster.local:3100
        basicAuth: false
        isDefault: false
        version: 1
        editable: false
      - name: Tempo
        type: tempo
        access: proxy
        orgId: 1
        url: http://tempo-service.tienda.svc.cluster.local:3200
        basicAuth: false
        isDefault: true
        version: 1
        editable: true
        apiVersion: 1
        uid: tempo
        jsonData:
          httpMethod: GET
          serviceMap:
            datasourceUid: prometheus
          tracesToLogsV2:
            datasourceUid: loki
            spanStartTimeShift: '-1h'
            spanEndTimeShift: '1h'
            filterByTraceID: true
            filterBySpanID: true
            tags: [ { key: 'service.name', value: 'job' } ]
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: tienda
spec:
  selector:
    app: grafana
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000