apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: tienda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        ports:
        - name: ui
          containerPort: 16686
        - name: http-traces
          containerPort: 4318 # Accepts traces in OpenTelemetry OTLP format
        - name: grpc-traces
          containerPort: 4317 # Accepts traces in OpenTelemetry OTLP format
        - name: jaeger-thrift
          containerPort: 14268
        - name: model-proto
          containerPort: 14250  
        - name: health-check
          containerPort: 14269     
        env: # Setting Environment Variables
          - name: COLLECTOR_OTLP_ENABLED
            value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
  namespace: tienda
spec:
  selector:
    app: jaeger
  ports:
  - name: ui
    protocol: TCP
    port: 16686
    targetPort: 16686
  - name: http-traces
    protocol: TCP
    port: 4318
    targetPort: 4318
  - name: grpc-traces
    protocol: TCP
    port: 4317
    targetPort: 4317
  - name: jaeger-thrift
    protocol: TCP
    port: 14268
    targetPort: 14268
  - name: model-proto
    protocol: TCP
    port: 14250
    targetPort: 14250
  - name: health-check
    protocol: TCP
    port: 14269
    targetPort: 14269