apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: tienda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        args:
        - --config.file=/etc/prometheus/prometheus.yml
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: tienda
data:
  prometheus.yml: |-
    global:
      scrape_interval: 10s
      evaluation_interval: 10s

    scrape_configs:
      - job_name: 'otel-collector'
        static_configs:
          - targets: ['otel-collector-service.tienda.svc.cluster.local:8889']

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: tienda
  annotations:
    prometheus.io/scrape: 'true'
spec:
  selector:
    app: prometheus
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090